// ============================================
// TRUSTFLOW - PREMIUM WIDGET PRESETS LIBRARY
// ============================================
// A collection of 10 production-ready widget styles
// that work seamlessly with embed.js

export const WIDGET_PRESETS = [
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean, distraction-free design with subtle shadows',
    category: 'modern',
    thumbnail: 'minimalist',
    popular: true,
    settings: {
      layout: 'grid',
      theme: 'light',
      cardTheme: 'light',
      corners: 'smooth',
      shadow: 'light',
      border: false,
      hoverEffect: 'lift',
      nameSize: 'medium',
      testimonialStyle: 'clean',
      animation: 'fade',
      speed: 'normal',
      cardSize: 'medium',
      maxCount: 6,
      gridRows: 2,
      wallPadding: 'large',
      showHeading: true,
      headingText: 'What our customers say',
      headingFont: 'Inter',
      headingColor: '#1e293b',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Real stories from real people',
      subheadingFont: 'Inter',
      subheadingColor: '#64748b',
      carouselFocusZoom: false,
      carouselSameSize: true,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'dark-glass',
    name: 'Dark Glassmorphism',
    description: 'Premium dark mode with frosted glass effect',
    category: 'premium',
    thumbnail: 'dark-glass',
    popular: true,
    settings: {
      layout: 'grid',
      theme: 'dark',
      cardTheme: 'dark',
      corners: 'round',
      shadow: 'strong',
      border: true,
      hoverEffect: 'glow',
      nameSize: 'medium',
      testimonialStyle: 'clean',
      animation: 'scale',
      speed: 'normal',
      cardSize: 'medium',
      maxCount: 9,
      gridRows: 3,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'Trusted by thousands',
      headingFont: 'Poppins',
      headingColor: '#f8fafc',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Join our growing community',
      subheadingFont: 'Inter',
      subheadingColor: '#94a3b8',
      carouselFocusZoom: false,
      carouselSameSize: true,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'masonry-elegant',
    name: 'Masonry Grid',
    description: 'Pinterest-style staggered layout for variety',
    category: 'creative',
    thumbnail: 'masonry',
    popular: false,
    settings: {
      layout: 'masonry',
      theme: 'light',
      cardTheme: 'light',
      corners: 'smooth',
      shadow: 'medium',
      border: true,
      hoverEffect: 'scale',
      nameSize: 'medium',
      testimonialStyle: 'bubble',
      animation: 'slideUp',
      speed: 'normal',
      cardSize: 'medium',
      maxCount: 12,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'Wall of Love',
      headingFont: 'Playfair Display',
      headingColor: '#1e293b',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Stories that inspire us every day',
      subheadingFont: 'Inter',
      subheadingColor: '#64748b',
      carouselFocusZoom: false,
      carouselSameSize: false,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'carousel-spotlight',
    name: 'Carousel Spotlight',
    description: 'Smooth auto-scrolling slider with focus zoom',
    category: 'interactive',
    thumbnail: 'carousel',
    popular: true,
    settings: {
      layout: 'carousel',
      theme: 'transparent',
      cardTheme: 'light',
      corners: 'round',
      shadow: 'strong',
      border: false,
      hoverEffect: 'lift',
      nameSize: 'large',
      testimonialStyle: 'clean',
      animation: 'fade',
      speed: 'normal',
      cardSize: 'large',
      maxCount: 10,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'What people are saying',
      headingFont: 'Montserrat',
      headingColor: '#0f172a',
      headingBold: true,
      showSubheading: false,
      subheadingText: '',
      subheadingFont: 'Inter',
      subheadingColor: '#64748b',
      carouselFocusZoom: true,
      carouselSameSize: true,
      autoScroll: true,
      scrollSpeed: 4,
      popupsEnabled: false
    }
  },
  {
    id: 'single-highlight',
    name: 'Single Highlight',
    description: 'Feature one powerful testimonial at a time',
    category: 'simple',
    thumbnail: 'single',
    popular: false,
    settings: {
      layout: 'carousel',
      theme: 'transparent',
      cardTheme: 'light',
      corners: 'round',
      shadow: 'strong',
      border: true,
      hoverEffect: 'none',
      nameSize: 'large',
      testimonialStyle: 'quote',
      animation: 'fade',
      speed: 'slow',
      cardSize: 'large',
      maxCount: 5,
      wallPadding: 'large',
      showHeading: true,
      headingText: 'Featured Review',
      headingFont: 'Crimson Text',
      headingColor: '#1e293b',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Hand-picked by our team',
      subheadingFont: 'Inter',
      subheadingColor: '#64748b',
      carouselFocusZoom: false,
      carouselSameSize: true,
      autoScroll: true,
      scrollSpeed: 6,
      popupsEnabled: false
    }
  },
  {
    id: 'bento-grid',
    name: 'Bento Grid',
    description: 'Modern asymmetric layout like Apple keynotes',
    category: 'modern',
    thumbnail: 'bento',
    popular: true,
    settings: {
      layout: 'grid',
      theme: 'light',
      cardTheme: 'light',
      corners: 'round',
      shadow: 'medium',
      border: false,
      hoverEffect: 'scale',
      nameSize: 'medium',
      testimonialStyle: 'clean',
      animation: 'pop',
      speed: 'fast',
      cardSize: 'medium',
      maxCount: 6,
      gridRows: 2,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'Loved by everyone',
      headingFont: 'DM Sans',
      headingColor: '#0f172a',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'See why teams choose us',
      subheadingFont: 'DM Sans',
      subheadingColor: '#64748b',
      carouselFocusZoom: false,
      carouselSameSize: false,
      autoScroll: false,
      popupsEnabled: true,
      popupPosition: 'bottom-right',
      popupDelay: 3,
      popupDuration: 5,
      popupGap: 15,
      popupMessage: '🎉 New review!'
    }
  },
  {
    id: 'twitter-style',
    name: 'Twitter Style',
    description: 'Social media inspired card design',
    category: 'social',
    thumbnail: 'twitter',
    popular: false,
    settings: {
      layout: 'masonry',
      theme: 'light',
      cardTheme: 'light',
      corners: 'smooth',
      shadow: 'light',
      border: true,
      hoverEffect: 'lift',
      nameSize: 'small',
      testimonialStyle: 'clean',
      animation: 'slideUp',
      speed: 'fast',
      cardSize: 'compact',
      maxCount: 12,
      wallPadding: 'small',
      showHeading: true,
      headingText: 'What people tweet about us',
      headingFont: 'Inter',
      headingColor: '#14171a',
      headingBold: true,
      showSubheading: false,
      subheadingText: '',
      subheadingFont: 'Inter',
      subheadingColor: '#657786',
      carouselFocusZoom: false,
      carouselSameSize: false,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'linkedin-pro',
    name: 'LinkedIn Professional',
    description: 'Corporate-ready professional testimonials',
    category: 'business',
    thumbnail: 'linkedin',
    popular: false,
    settings: {
      layout: 'list',
      theme: 'light',
      cardTheme: 'light',
      corners: 'smooth',
      shadow: 'light',
      border: true,
      hoverEffect: 'lift',
      nameSize: 'medium',
      testimonialStyle: 'clean',
      animation: 'fade',
      speed: 'normal',
      cardSize: 'medium',
      maxCount: 6,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'Recommendations',
      headingFont: 'Source Sans Pro',
      headingColor: '#000000',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'What professionals say about working with us',
      subheadingFont: 'Source Sans Pro',
      subheadingColor: '#666666',
      carouselFocusZoom: false,
      carouselSameSize: true,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'video-first',
    name: 'Video Showcase',
    description: 'Optimized for video testimonials with vertical scroll',
    category: 'video',
    thumbnail: 'video-first',
    popular: true,
    settings: {
      layout: 'grid',
      theme: 'dark',
      cardTheme: 'dark',
      corners: 'round',
      shadow: 'strong',
      border: false,
      hoverEffect: 'scale',
      nameSize: 'medium',
      testimonialStyle: 'clean',
      animation: 'scale',
      speed: 'normal',
      cardSize: 'large',
      maxCount: 6,
      gridRows: 2,
      wallPadding: 'medium',
      showHeading: true,
      headingText: 'Watch their stories',
      headingFont: 'Montserrat',
      headingColor: '#ffffff',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Real customers, real experiences',
      subheadingFont: 'Inter',
      subheadingColor: '#a1a1aa',
      carouselFocusZoom: false,
      carouselSameSize: true,
      autoScroll: false,
      popupsEnabled: false
    }
  },
  {
    id: 'gradient-vibrant',
    name: 'Vibrant Gradient',
    description: 'Eye-catching colorful cards with gradient accents',
    category: 'creative',
    thumbnail: 'gradient',
    popular: false,
    settings: {
      layout: 'carousel',
      theme: 'transparent',
      cardTheme: 'light',
      corners: 'round',
      shadow: 'strong',
      border: false,
      hoverEffect: 'glow',
      nameSize: 'medium',
      testimonialStyle: 'bubble',
      animation: 'pop',
      speed: 'fast',
      cardSize: 'medium',
      maxCount: 8,
      wallPadding: 'medium',
      showHeading: true,
      headingText: '💜 Customer Love',
      headingFont: 'Poppins',
      headingColor: '#7c3aed',
      headingBold: true,
      showSubheading: true,
      subheadingText: 'Spreading joy, one review at a time',
      subheadingFont: 'Poppins',
      subheadingColor: '#a78bfa',
      carouselFocusZoom: true,
      carouselSameSize: true,
      autoScroll: true,
      scrollSpeed: 3,
      popupsEnabled: true,
      popupPosition: 'bottom-left',
      popupDelay: 2,
      popupDuration: 4,
      popupGap: 8,
      popupMessage: '✨ Fresh feedback!'
    }
  }
];

// Preset categories for filtering
export const PRESET_CATEGORIES = [
  { id: 'all', name: 'All Styles', icon: 'Sparkles' },
  { id: 'popular', name: 'Popular', icon: 'TrendingUp' },
  { id: 'modern', name: 'Modern', icon: 'Zap' },
  { id: 'premium', name: 'Premium', icon: 'Crown' },
  { id: 'creative', name: 'Creative', icon: 'Palette' },
  { id: 'interactive', name: 'Interactive', icon: 'MousePointer' },
  { id: 'social', name: 'Social', icon: 'Share2' },
  { id: 'business', name: 'Business', icon: 'Briefcase' },
  { id: 'video', name: 'Video', icon: 'Video' }
];

// Get preset by ID
export const getPresetById = (id) => WIDGET_PRESETS.find(p => p.id === id);

// Get presets by category
export const getPresetsByCategory = (category) => {
  if (category === 'all') return WIDGET_PRESETS;
  if (category === 'popular') return WIDGET_PRESETS.filter(p => p.popular);
  return WIDGET_PRESETS.filter(p => p.category === category);
};

// Thumbnail color schemes for preview cards
export const PRESET_THUMBNAILS = {
  'minimalist': {
    bg: 'bg-gradient-to-br from-slate-50 to-slate-100',
    accent: 'bg-slate-200',
    cardBg: 'bg-white',
    textColor: 'text-slate-700'
  },
  'dark-glass': {
    bg: 'bg-gradient-to-br from-slate-900 to-slate-800',
    accent: 'bg-violet-500/20',
    cardBg: 'bg-slate-800/50',
    textColor: 'text-white'
  },
  'masonry': {
    bg: 'bg-gradient-to-br from-amber-50 to-orange-50',
    accent: 'bg-amber-200',
    cardBg: 'bg-white',
    textColor: 'text-amber-900'
  },
  'carousel': {
    bg: 'bg-gradient-to-br from-blue-50 to-indigo-50',
    accent: 'bg-blue-400',
    cardBg: 'bg-white',
    textColor: 'text-blue-900'
  },
  'single': {
    bg: 'bg-gradient-to-br from-emerald-50 to-teal-50',
    accent: 'bg-emerald-300',
    cardBg: 'bg-white',
    textColor: 'text-emerald-900'
  },
  'bento': {
    bg: 'bg-gradient-to-br from-pink-50 to-rose-50',
    accent: 'bg-pink-300',
    cardBg: 'bg-white',
    textColor: 'text-pink-900'
  },
  'twitter': {
    bg: 'bg-gradient-to-br from-sky-50 to-blue-100',
    accent: 'bg-sky-400',
    cardBg: 'bg-white',
    textColor: 'text-sky-900'
  },
  'linkedin': {
    bg: 'bg-gradient-to-br from-blue-600 to-blue-800',
    accent: 'bg-white/20',
    cardBg: 'bg-white',
    textColor: 'text-white'
  },
  'video-first': {
    bg: 'bg-gradient-to-br from-purple-900 to-violet-900',
    accent: 'bg-violet-500',
    cardBg: 'bg-slate-800',
    textColor: 'text-white'
  },
  'gradient': {
    bg: 'bg-gradient-to-br from-violet-500 via-purple-500 to-pink-500',
    accent: 'bg-white/30',
    cardBg: 'bg-white/90',
    textColor: 'text-white'
  }
};

export default WIDGET_PRESETS;
